name: benji_vendor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.3.1
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_pw_validator: ^1.6.0
  otp: ^3.1.4
  otp_text_field: ^1.1.3
  get: ^4.6.5
  permission_handler: ^10.3.0
  image_picker: ^1.0.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/images/logo/logo-icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/login/
    - assets/images/logo/
    - assets/images/profile/
    - assets/images/splash screen/
    - assets/images/vendor/
    - assets/images/food/
    - assets/images/customer/
    - assets/animations/forgot password/
    - assets/animations/no internet/
    - assets/animations/splash screen/
    - assets/animations/successful/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
